# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57acb50cdf48a8439955824e9faf6925fb52726af8379b1e64e7747d73ca5d2f91222f5ee63fd0119bc6d4c7d42d9783d5d14a83e4012fac87ce3983bfbb672b

test:
  secret_key_base: 81355a617ec52c8e56dfd9c7dddf7c3ccc23b9986a3fbb66de5df8e9a11f02b409349c71ef59c144c53fded8ea90265a990f8ad2d62709c6e3c0ae711df3ca87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
